# Generated by Django 4.2 on 2023-04-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iMagazine', '0004_alter_productcard_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name': 'тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='productcard',
            options={'verbose_name': 'карточка товара', 'verbose_name_plural': 'Карточки товаров'},
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='desription',
            new_name='description',
        ),
    ]
